### ISSUE TITLE
Basic support for riscv64

### ISSUE THREAD

**Issue by felixonmars** [simd-lite/simd-json#303] opened 2023-07-29 17:01 UTC
I am trying to build this library on riscv64 with `allow-non-simd` set, but unfortunately it fails to load some sse42 bits here and there:

```
error[E0432]: unresolved import `super::parse_eight_digits_unrolled`
 --> /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.4/src/numberparse/correct.rs:7:43
  |
7 | use super::{is_made_of_eight_digits_fast, parse_eight_digits_unrolled};
  |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `parse_eight_digits_unrolled` in `numberparse`

error[E0433]: failed to resolve: could not find `x86` in `imp`
   --> /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.4/src/lib.rs:216:27
    |
216 | use simdutf8::basic::imp::x86::sse42::ChunkedUtf8ValidatorImp;
    |                           ^^^ could not find `x86` in `imp`

error[E0432]: unresolved import `arch`
 --> /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.4/src/sse42/deser.rs:7:5
  |
7 | use arch::{
  |     ^^^^ help: a similar path exists: `std::arch`

error[E0412]: cannot find type `__m128i` in this scope
  --> /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.4/src/sse42/stage1.rs:36:52
   |
36 | pub const SIMDJSON_PADDING: usize = mem::size_of::<__m128i>() * 2;
   |                                                    ^^^^^^^ not found in this scope

error[E0412]: cannot find type `__m128i` in this scope
......
```

It seems the library loads some sse42 code even when the feature isn't present: https://github.com/simd-lite/simd-json/blob/main/src/lib.rs#L216

Any idea how to improve the situation and get the non-simd version build before we get started on real SIMD support?

**Comment by Licenser** [comment] 2023-10-09 12:38
Ill close this as a duplicate of #322 since it covers the wider improvement

**Closed by Licenser** 2023-10-09 12:38 UTC
